# Generated by Django 4.0.1 on 2022-01-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='isFrontPage',
            new_name='showOnFrontPage',
        ),
        migrations.AlterField(
            model_name='image',
            name='imageSource',
            field=models.ImageField(upload_to='static/pics/'),
        ),
    ]
