# Generated by Django 4.0.1 on 2022-01-20 04:00

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0003_alter_image_imagesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageSource',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=0, size=[640, 640], upload_to='images/'),
        ),
    ]
