# Generated by Django 4.0.1 on 2022-01-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0004_alter_image_imagesource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageSource',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
