# Generated by Django 4.0.1 on 2022-12-18 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_gallery', '0005_alter_image_imagesource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='foobar',
        ),
    ]
