# Generated by Django 4.0.1 on 2022-07-25 22:57

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[(blog.models.Post.Status['PUBLISHED'], 'Published'), (blog.models.Post.Status['DRAFT'], 'Draft')], default=blog.models.Post.Status['DRAFT'], max_length=10),
        ),
    ]
