# Generated by Django 4.0.1 on 2022-07-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='great_divide/featured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
